apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-router-config
  namespace: kube-system
data:
  cni-conf.json: |
    {
      "name": "pod-network",
      "cniVersion": "0.3.1",
      "plugins":[
        {
          "name": "kube-router",
          "type": "bridge",
          "bridge": "kube-bridge",
          "isDefaultGateway": true,
          "mtu": ${network_mtu},
          "ipam": {
            "type": "host-local"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
